import { randomUUID } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { join, posix } from 'node:path';
import { recoverUpdateState, writeUpdateState } from './state';

export const STALE_LOCK_MIN_AGE_MS = 60_000;
export interface InstallOptions { cacheRoot: string; version: string; packageSpec: string; sourceDir: string; entry?: string; pid?: number; now?:()=>number; run?: (cmd:string,args:string[],opts:any)=>Promise<{status:number}>; rename?: (a:string,b:string)=>void; download?: (url:string,init?:RequestInit)=>Promise<Response>; }
export interface LockOwner { token:string; pid:number; createdAt:number; stage:string; }
export class UpdateError extends Error { constructor(public code:string,message:string){super(message);} }
function lockPath(r:string){return join(r,'update.lock');}
function acquire(root:string, o:InstallOptions): LockOwner { mkdirSync(root,{recursive:true}); const now=(o.now??Date.now)(), owner={token:randomUUID(),pid:o.pid??process.pid,createdAt:now,stage:'staging'}; try { writeFileSync(lockPath(root),JSON.stringify(owner),{flag:'wx'}); return owner; } catch { try { const old=JSON.parse(readFileSync(lockPath(root),'utf8')) as LockOwner; const age=now-old.createdAt; let alive=true; try { process.kill(old.pid,0); } catch { alive=false; } if (!alive && age>STALE_LOCK_MIN_AGE_MS) { rmSync(lockPath(root),{force:true}); writeFileSync(lockPath(root),JSON.stringify(owner),{flag:'wx'}); return owner; } } catch {} throw new UpdateError('lock','update lock is busy'); } }
function release(root:string, owner:LockOwner){try { const current=JSON.parse(readFileSync(lockPath(root),'utf8')); if(current.token===owner.token) rmSync(lockPath(root),{force:true}); } catch {} }
function verifyPackage(dir:string, entry?:string){ let p; try { p=JSON.parse(readFileSync(join(dir,'package.json'),'utf8')); } catch { throw new UpdateError('verify','invalid package.json'); } if(p.name!=='opencode-oceanus' || typeof p.version!=='string') throw new UpdateError('verify','invalid package metadata'); const ep=entry??p.main??p.module??'dist/index.js'; if(!existsSync(join(dir,ep))) throw new UpdateError('verify','package entry is missing'); return {packageJson:p,entry:ep}; }
function safeTarPath(name:string) { if(!name || name.includes('\0') || name.includes('\\') || name.startsWith('/') || /^[A-Za-z]:[\\/]/.test(name) || name.startsWith('//')) throw new UpdateError('download','unsafe archive path'); const p=posix.normalize(name); if(p==='..'||p.startsWith('../')) throw new UpdateError('download','unsafe archive path'); return p; }
function extractTar(data:Buffer, staging:string) { for(let off=0; off+512<=data.length;) { const h=data.subarray(off,off+512); if(h.every(x=>x===0)) break; const name=h.subarray(0,100).toString().replace(/\0.*$/,''); const size=parseInt(h.subarray(124,136).toString().replace(/\0.*$/,'').trim()||'0',8); const type=h[156]; const path=safeTarPath(name); if(!path.startsWith('package/')) throw new UpdateError('download','archive must contain package prefix'); const rel=path.slice(8); if(!rel) { off+=512+Math.ceil(size/512)*512; continue; } const out=join(staging,rel); if(type===1||type===2||type===3||type===4||type===5||type===6||type===7) { if(type!==5) throw new UpdateError('download','links are not allowed'); mkdirSync(out,{recursive:true}); } else if(type===0) { mkdirSync(join(out,'..'),{recursive:true}); writeFileSync(out,data.subarray(off+512,off+512+size)); } else throw new UpdateError('download','unsupported archive entry'); off+=512+Math.ceil(size/512)*512; } }
export async function installStaged(o:InstallOptions){ const owner=acquire(o.cacheRoot,o); const staging=join(o.cacheRoot,`staging-${owner.token}`); const live=join(o.cacheRoot,'live'); const quarantine=join(o.cacheRoot,'quarantine'); const partial=join(o.cacheRoot,'downloads',`${o.version}.tgz.partial`); const mv=o.rename??renameSync; try { recoverUpdateState(o.cacheRoot); mkdirSync(join(o.cacheRoot,'downloads'),{recursive:true}); writeUpdateState(o.cacheRoot,{phase:'download',version:o.version}); const url=`https://registry.npmjs.org/opencode-oceanus/-/opencode-oceanus-${encodeURIComponent(o.version)}.tgz`; const ac=new AbortController(); const timer=setTimeout(()=>ac.abort(),30_000); let response:Response; try { response=await (o.download??fetch)(url,{signal:ac.signal}); } finally { clearTimeout(timer); } if(!response.ok) throw new UpdateError('download',`download failed: ${response.status}`); writeFileSync(partial,Buffer.from(await response.arrayBuffer())); mkdirSync(staging,{recursive:true}); extractTar(gunzipSync(readFileSync(partial)),staging); rmSync(partial,{force:true}); const run=o.run??(async(cmd,args,opts)=>{const p=Bun.spawn([cmd,...args],opts); return {status:await p.exited};}); const env={PATH:process.env.PATH??'',HOME:process.env.HOME??'',TMPDIR:process.env.TMPDIR??''}; const result=await run('bun',['install','--ignore-scripts'],{cwd:staging,env}); if(result.status!==0) throw new UpdateError('install','bun install failed'); verifyPackage(staging,o.entry); writeUpdateState(o.cacheRoot,{phase:'staging',staging,live,version:o.version}); if(existsSync(live)) { mv(live,quarantine); writeUpdateState(o.cacheRoot,{phase:'quarantine',staging,quarantine,live,version:o.version}); } mv(staging,live); writeUpdateState(o.cacheRoot,{phase:'live',live,version:o.version}); if(existsSync(quarantine)) rmSync(quarantine,{recursive:true,force:true}); writeUpdateState(o.cacheRoot,{phase:'committed',live,version:o.version}); rmSync(join(o.cacheRoot,'update-state.json'),{force:true}); return live; } catch(e) { rmSync(partial,{force:true}); if(existsSync(staging)) rmSync(staging,{recursive:true,force:true}); if(!existsSync(live)&&existsSync(quarantine)){ try { mv(quarantine,live); } catch {} } writeUpdateState(o.cacheRoot,{phase:'update_failed',version:o.version}); throw e; } finally { release(o.cacheRoot,owner); } }
export const installUpdate = installStaged;
